local command_ids = {
  toggle_file_tree = "com.example.{{PROJECT_NAME}}.toggleFileTree",
  insert_header = "com.example.{{PROJECT_NAME}}.insertHeader",
  wrap_selection = "com.example.{{PROJECT_NAME}}.wrapSelection"
}

local function comment_prefix_for(language_id)
  if language_id == "python" or language_id == "shell" or language_id == "yaml" then
    return "#"
  end
  return "//"
end

local function active_editor_or_warn()
  local editor = tina.editor.getActiveEditor()
  if editor == nil then
    tina.log.warn("No active editor")
    return nil
  end
  return editor
end

function on_toggle_file_tree()
  local ok, err = tina.commands.execute("view.toggleFileTree")
  if ok then
    tina.log.info("Forwarded host command: view.toggleFileTree")
    return
  end
  tina.log.warn("Failed to execute host command: " .. tostring(err))
end

function on_insert_header()
  local editor = active_editor_or_warn()
  if editor == nil then
    return
  end

  local file_name = editor.fileName or "unknown"
  local prefix = comment_prefix_for(editor.languageId)
  local header = prefix .. " Generated by {{PROJECT_NAME}} for " .. file_name .. "\n"
  local ok = tina.editor.insertText(header, 0, 0)
  if ok then
    tina.log.info("Inserted starter header into " .. file_name)
  else
    tina.log.warn("insertText returned false")
  end
end

function on_wrap_selection()
  local editor = active_editor_or_warn()
  if editor == nil then
    return
  end

  local prefix = comment_prefix_for(editor.languageId)
  local selection = tina.editor.getSelection()
  local selected_text = selection and selection.text or ""
  if selected_text ~= "" then
    local replacement = prefix .. " BEGIN\n" .. selected_text .. "\n" .. prefix .. " END"
    local ok = tina.editor.replaceSelection(replacement)
    if ok then
      tina.log.info("Wrapped current selection")
    else
      tina.log.warn("replaceSelection returned false")
    end
    return
  end

  local ok = tina.editor.insertText(prefix .. " TODO: plugin command ran here\n")
  if ok then
    tina.log.info("Inserted fallback text at cursor")
  else
    tina.log.warn("Fallback insertText returned false")
  end
end

local function register_command(command_id, callback_name, title)
  local ok, err = tina.commands.register(command_id, callback_name, title)
  if ok then
    tina.log.info("Registered plugin command: " .. command_id)
    return
  end
  tina.log.warn("Register command failed: " .. tostring(err))
end

tina.log.info("{{PROJECT_NAME}} command starter loaded")
tina.ui.showMessage("{{PROJECT_NAME}} loaded")

register_command(command_ids.toggle_file_tree, "on_toggle_file_tree", "Toggle File Tree")
register_command(command_ids.insert_header, "on_insert_header", "Insert Starter Header")
register_command(command_ids.wrap_selection, "on_wrap_selection", "Wrap Selection")
